### PR TITLE
German localisation 

### PR DESCRIPTION
**Pull request by hubertba**

### CODE REVIEW

**Comment by hubertba** [comment]
oh ... I saw you already have a translation ...

If you want I can merge and proof-read ... If not ... just drop the PR

**Comment by hubertba** [comment]
I was to slow with my contribution :-(

should I merge and proof-read ?

**Comment by mufasaYC** [comment]
Hey, if you could resolve the conflicts with proof reading and helping with what is the best for the app, that would be absolutely amazing! Thank you for taking out time and doing this, really appreciate it!

**Comment by hubertba** [comment]
since your app is named Task .. and it is a understood word .. I would not tanslate it. same with Todo
- is it Task Plus or Task+ ? ... I have unified it to Task+

**Comment by hubertba** [comment]
If you have a TestFlight Available .. I could also check if the translations match the context :-)

**Comment by mufasaYC** [comment]
The branding for the app is "Tasks", could you change it to reflect the same. 
"Tasks Plus" without localising it, or I could do it, let me know! Thank you @hubertba, I will share the app with you for testing once I upload it.

**Comment by hubertba** [comment]
Updated Tasks Plus

**Comment by mufasaYC** [comment]
Thank you @hubertba, glad to have this merged in!

**Comment by hubertba** [comment]
Hi. Any TestFlight version on the way to check the context of the translations?

**Pull request merged**
